### PR TITLE
Make ThumbColorActive visible for Switch

### LINKED ISSUE #2016: Switch property ThumbColorActive set to invisible in blocks
**Describe the bug**

The block for the ThumbColorActive does not appears in the Blocks Editor. The property is fine in the Designer.

Forum report:
https://community.appinventor.mit.edu/t/switch-property-missing-thumbcoloractive-from-block-view/3207

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Set/Get blocks should appear in the Blocks Editor for this property, same as the other Thumb/Track colors.

**Steps to reproduce**

Create a new project
Add a Switch to the project
Switch to Blocks Editor
Click the new Switch and look at the property blocks.

### PR DESCRIPTION
**Pull request by SusanRatiLane**
Fixes #2016

### CODE REVIEW

File: appinventor/components/src/com/google/appinventor/components/runtime/Switch.java [hunk 1]
```diff
@@ -94,7 +94,7 @@ private ColorStateList createSwitchColors(int active_color, int inactive_color)
    *
    * @return  thumb RGB color with alpha
    */
-  @SimpleProperty(category = PropertyCategory.APPEARANCE, userVisible = false)
+  @SimpleProperty(category = PropertyCategory.APPEARANCE, userVisible = true)
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Switch.java]: userVisible = true is the default, so you could just remove the setting of the field here.

Comment (SusanRatiLane) [reply appinventor/components/src/com/google/appinventor/components/runtime/Switch.java]: Done
