### PR TITLE
Fix blocks project switch

### LINKED ISSUE #3072: Block editor freezing when switching between projects
**Describe the bug**

When switching back and forth between projects, the block editor becomes unmovable and the accessories on the right disappear. This can be fixed by changing the browser size (fullscreen/unfullscreen).

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Blocks editor should function as it does upon opening a fresh project. Should be able to drag the entire display around to access other blocks, and accessories such as backpack should be visible.

**Steps to reproduce**

1. Open project A to the blocks editor
2. Switch to project B and open the blocks editor
3. Switch back to the block editor of project A

### PR DESCRIPTION
**Pull request by mjgallag**
General items:

- [ ] I have updated the relevant documentation files under docs/
- [x] My code follows the:
    - [x] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [x] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [x] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [ ] I branched from `ucr`
- [ ] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [ ] I have updated the corresponding version number in appinventor/components/src/.../common/YaVersion.java
- [ ] I have updated the corresponding upgrader in appinventor/appengine/src/.../client/youngandroid/YoungAndroidFormUpgrader.java (components only)
- [ ] I have updated the corresponding entries in appinventor/blocklyeditor/src/versioning.js

For all other changes:

- [x] I branched from `master`
- [x] My pull request has `master` as the base

What does this PR accomplish?

Fixes issues when switching between projects that were both left on blocks view.

Steps to reproduce:
1. Click Project 1
2. Click Blocks
3. Click ← to return to project list
4. Click Project 2
5. Click Blocks
6. Click ← to return to project list
7. Click Project 1 — first click does nothing
   - fixed by 3f095115f
8. Click Project 1 again — opens but Blockly workspace is blank & scroll position is reset
   - fixed by c6c437d8e & 7aadf6b70 (scroll issue only visible after c6c437d8e)

Also included is dca637119 which skips UISettingsWizard delay when not animating, reusing animation tracking from c6c437d8e.

Fixes #3072.

### CODE REVIEW

**Comment by ewpatton** [comment]
@mjgallag Do you think it is preferable to keep these commits separate, or should we squash them after review?

**Comment by mjgallag** [comment]
I think separate.

File: appinventor/appengine/src/com/google/appinventor/client/Ode.java [hunk 1]
```diff
@@ -1238,8 +1238,8 @@ public void setCurrentFileEditor(FileEditor fileEditor) {
     LOG.info("Ode: Setting current file editor to " + currentFileEditor.getFileId());
     if (currentFileEditor instanceof YaFormEditor) {
       sourceStructureBox.show(((YaFormEditor) currentFileEditor).getForm());
-      switchToDesignView();
     }
+    switchToDesignView();
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/Ode.java]: Hmm. I wonder if maybe we should change the name of this function to something else, e.g., `switchToProjectEditor()`. My initial thought when looking at this change is that of course the designer view should only be shown for YaFormEditor (or really, DesignerEditor), except DesignView here references to the general project editor entry in the DeckPanel and not the Designer view that we normally talk about when working on App Inventor projects. I'm worried if we keep the name the same we will reintroduce this error in the future after we've forgotten this issue.

**Comment by ewpatton** [comment]
I generally agree with this change other than my other comment. Another thing we can think about is whether the DeckPanel animation really adds anything since most of this code is just to work around responding to the fact that we cannot get a notification of whether that is done or not. If it doesn't really add value we could turn it off.

File: appinventor/appengine/src/com/google/appinventor/client/Ode.java (hunk 1 above)
Comment (mjgallag) [reply appinventor/appengine/src/com/google/appinventor/client/Ode.java]: I agree, done but I took it further and renamed `designTabIndex` to `projectEditorTabIndex` too, see https://github.com/mit-cml/appinventor-sources/pull/3749/changes/7d605b9767b1e59ee7ba2db45a43927c7cd57d5d.

**Comment by mjgallag** [comment]
> I generally agree with this change other than my other comment. Another thing we can think about is whether the DeckPanel animation really adds anything since most of this code is just to work around responding to the fact that we cannot get a notification of whether that is done or not. If it doesn't really add value we could turn it off.

I will submit a pr for this shortly.

**Comment by mjgallag** [comment]
@ewpatton so I can merge this to master as separate commits now? Just wanted to double check since it will be going to `ai2-test` and I don't quite understand the flow.
