### PR TITLE
Fix Road map tiles not rendering due to OSM redirects

### LINKED ISSUE #3723: Map component - no map displayed
An app which was working for years using Openstreetmap (OSM) road map type does not show any map anymore. As described in a post in the MIT app inventor forum [(link)](https://community.appinventor.mit.edu/t/map-not-displayed/156514/4), no map is shown in the compiled app. Especially when one switches back to road map type (from a different screen or a map component using a different map type) one gets an empty map.
This behaviour is reproducible and happened seemingly in several published apps since about September 2025.
I have tested this in online and offline app inventor, no difference in the build apps.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Projects Explorer
- [ ] Android Companion
- [ ] iOS Companion
- [x ] Android Compiled APK/AAB
- [ ] iOS Compiled IPA
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**
Show a map as defined by the map component (using map type road and the default tile server from Openstreetmap).

**Steps to reproduce**
As described above: Build test app only with a layout to show a map component (map type road).

### PR DESCRIPTION
**Pull request by Akashgite1**
General items:

- [ ] I have updated the relevant documentation files under docs/
- [X] My code follows the:
    - [X] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [ ] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [ ] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [ ] I branched from `ucr`
- [ ] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [ ] I have updated the corresponding version number in appinventor/components/src/.../common/YaVersion.java
- [ ] I have updated the corresponding upgrader in appinventor/appengine/src/.../client/youngandroid/YoungAndroidFormUpgrader.java (components only)
- [ ] I have updated the corresponding entries in appinventor/blocklyeditor/src/versioning.js

For all other changes:

- [X] I branched from `master`
- [X] My pull request has `master` as the base

What does this PR accomplish?

*Description*
This PR fixes an issue where the Road map type renders as a blank or grey map.

OpenStreetMap tile servers now return HTTP redirects, which are not reliably
handled by the osmdroid version used by App Inventor. As a result, Road map
tiles fail to load, especially after switching map types (Road → Aerial → Road).

The fix replaces the redirecting endpoint with explicit OpenStreetMap tile
subdomains (a/b/c.tile.openstreetmap.org) and clears the tile cache when
switching back to Road, restoring correct behavior across Companion and
compiled apps.

Fixes #3723.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by Akashgite1** [comment]
Verified locally on Android Companion and compiled APK.

Switching map types now works correctly:
- Road map loads as expected
- Switching Road → Aerial → Road no longer results in a blank/grey map

image

Screenshots below show:
1) Initial Road map state


2) Aerial map view


3) Road map correctly reloaded after switching back

File: appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java [hunk 1]
```diff
@@ -452,12 +452,28 @@ public String getTileURLString(MapTile aTile) {
     return tileSource;
   }
 
+  private ITileSource getRoadTileSource() {
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java]: Rather than constructing this as a new object every time, create a static final field. Also, make sure to include the attribution string "© OpenStreetMap contributors" in the extra argument to XYTileSource to provide proper attribution.

File: appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java [hunk 2]
```diff
@@ -452,12 +452,28 @@ public String getTileURLString(MapTile aTile) {
...
+    );
+  }
+
   @Override
   public void setMapTypeAbstract(MapType type) {
     tileType = type;
     switch (type) {
       case Road:
-        view.setTileSource(TileSourceFactory.MAPNIK);
+        view.getTileProvider().clearTileCache();
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/util/NativeOpenStreetMapController.java]: It looks like clearTileCache is indirectly called by setTileSource, so this is probably unnecessary.

**Comment by Akashgite1** [comment]
Thanks for the suggestions!

I've updated the implementation to:
- Use a static final XYTileSource for the Road map
- Include proper "© OpenStreetMap contributors" attribution
- Remove the explicit clearTileCache call since setTileSource already handles it

Please let me know if this looks good now.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

**Review by ewpatton — APPROVED** [review]
LGTM
