### PR TITLE
Fix folder name validation to replace invalid characters and correct error messages (#3345)

### LINKED ISSUE #3345: New folder dialog does not handle name validation correctly
**Describe the bug**

The new folder wizard uses the project name validation methods and displays the related error messages. In addition to the error messages referencing "project" instead of "folder," they also don't correctly describe the wizard behavior. The folder wizard does not automatically remove or replace invalid characters, e.g. replacing " " with "_", and the error message says it will.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [X] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Folder name validation should handle automatically handle invalid characters the same way project name validation does, and the strings referencing projects should be fixed.

**Steps to reproduce**

Click the new folder button on the project list and try some names.

### PR DESCRIPTION
**Pull request by d1vyanshu-kumar**
General items:

- [X] My code follows the:
    - [X] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [X] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [X] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [X] I branched from `master`
- [X] My pull request has `mster` as the base

For all other changes:

- [X] I branched from `master`
- [X] My pull request has `master` as the base

What does this PR accomplish?

1. **Enhance `TextValidators.java`**:
   - Added `getFolderErrorMessage` method to validate folder names and return appropriate error messages.
   - Added `getFolderWarningMessages` method to provide warnings for folder names containing spaces and suggest a modified name.

2. **Update Error Messages in `OdeMessages.java`**:
   - Added new error messages specific to folder names:
  
3. **Modify `NewFolderWizard.java`**:
   - Changed the validation method to use `TextValidators.getFolderErrorMessage` and `TextValidators.getFolderWarningMessages` instead of project name validators.
   - Updated the `addFolder` method to:
     - Automatically replace spaces with underscores in the folder name.
     - Use the corrected folder name for validation and creation.

Fixes #3345

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by d1vyanshu-kumar** [comment]
Hi @SusanRatiLane,

Could you please review my pull request?

Thank you!

**Comment by d1vyanshu-kumar** [comment]
Hi @SusanRatiLane, 
If you have time, please review this PR.
Thank you!

File: appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java [hunk 1]
```diff
@@ -253,6 +253,28 @@ public static String getErrorMessage(String filename){
...
   }
 
+  /**
+   * Returns an error message if the folder name is invalid.
+   * It checks if the folder name starts with a letter and contains only letters, numbers, and underscores.
+   * @param folderName The name of the folder to validate.
+   * @return String representing the error message, empty string if no error.
+   */
+  public static String getFolderErrorMessage(String folderName) {
+    String errorMessage = "";
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java:263]: Considering that the validation criteria for filenames and folder names is the same and we're only separating the methods out to return appropriate error messages, it might be better to make the actual validation a method that is called by both getFolderErrorMessage and get(File?)ErrorMessage.

**Comment by d1vyanshu-kumar** [comment]
@SusanRatiLane 

I made the necessary changes to fulfil fill above condition please review this and If there's anything that I missed or needs improvement, please let me know. I’m happy to make changes accordingly. 😃

- We had two methods doing the same check, so I made one method (validateName) to do it for both. 
- The enum is like a list of possible problems we can pick from.
- ValidationResult is a box that holds the problem and the fixed name, so we don’t lose anything.
- Each method now asks validateName for help and then picks the right message to show.

File: appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java (hunk 1 above)
Comment (d1vyanshu-kumar) [reply appinventor/appengine/src/com/google/appinventor/client/youngandroid/TextValidators.java]: @SusanRatiLane

I made the necessary changes to fulfil fill above condition please review this and If there's anything that I missed or needs improvement, please let me know. I’m happy to make changes accordingly. 😃

We had two methods doing the same check, so I made one method (validateName) to do it for both.
The enum is like a list of possible problems we can pick from.
ValidationResult is a box that holds the problem and the fixed name, so we don’t lose anything.
Each method now asks validateName for help and then picks the right message to show.

**Comment by SusanRatiLane** [comment]
@AppInventorWorkerBee ok tp est

**Comment by SusanRatiLane** [comment]
@AppInventorWorkerBee ok to test

**Review by SusanRatiLane — APPROVED** [review]
LGTM
