### PR TITLE
Fix not being able to modify collapsed blocks

### LINKED ISSUE #1964: Make generic breaks on collapsed blocks
**Describe the bug**

Using the Make Generic menu option on a collapsed block breaks the block and the undo stack.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Make Generic should properly update a collapsed block and the operation should be undoable with Undo command.

**Steps to reproduce**

1. Create a button
2. Create the Button1.Click event handler
3. Collapse the event handler
4. Right click on the block and select Make Generic
5. Attempt to interact with the block.

For examples see https://community.appinventor.mit.edu/t/a-problem-about-make-generic/1480?u=ewpatton

### PR DESCRIPTION
**Pull request by BeksOmega**
### Resolves

Closes #1964 

### Description

1) Adds an extra rendering step to the rendering pipeline in the case that the block is collapsed. This step makes sure that the block is in a proper collapsed state (e.g. all inputs are hidden) before re-rendering the block.

2) Fixes some bugs from core like https://github.com/google/blockly/issues/1967

3) Optimizes toString to make it super zippy. (Probably overkill, but it was fun)

#### Unit Tests
I wrote 40 unit tests covering:
* Connecting to Collapsed Blocks
* Disconnecting from Collapsed Blocks
* Modifying Collapsed Blocks
* toString

All tests pass, but they do not run with `ant tests`. It /should/ be pretty easy to get working with phantom (you just need to listen for when the tests_failed attribute changes, or send some sort of callback from the mocha.run function) I just don't know how to do it.

#### Manual Tests
I also did manual testing to confirm it works with generic blocks:
SpecificToGeneric
GenericToSpecific

#### Speed Tests
And I did speed tests to make sure my changes were still efficient.

1) I tested this new method of updating collapsed blocks vs the old method (i.e. expand, modify, collapse). Not surprisingly this method was much faster with an average of ~3ms vs ~1650ms with a large block stack.
2) I tested appending an input to a collapsed block vs appending an input to an expanded block. I did this because appending causes a re-render. These were very comparable with collapsed averaging 24.62ms and expanded averaging 34.37ms. And they both ranged from ~5ms to ~50mx
3) I tested collapsing a large block stack on master vs collapsing on this branch. Surprisingly this branch was about 2x faster with an average of 219.69ms vs 457.67ms.

So I think these changes should be good.

### Additional Info

This was just my first shot at it, so pull request comments are very much appreciated.

Also if anyone wants to pull this down and try and break it that would be awesome! I tried to give it a pretty thorough testing, but I'm touching some pretty core stuff here so more eyes are always welcome.

### CODE REVIEW

**Comment by ewpatton** [comment]
@BeksOmega You should be able to invoke mocha from within ant. If you do, I would also enable the mocha-junit-reporter so that the output can be shown along with the rest of the unit test reports.

**Comment by BeksOmega** [comment]
> You should be able to invoke mocha from within ant. If you do, I would also enable the mocha-junit-reporter so that the output can be shown along with the rest of the unit test reports.

@ewpatton So I did some more work to try and get it working, but still no dice. Just so you know, I don't know alot about node, so I could be totally wrong about what I think is happening.

When you say "invoke mocha" I assume that's going to mean the run the `mocha` command. I tried to get that working, but it was throwing errors about "Blockly is not defined". 

Running the webpage this isn't a problem, because `Blockly` just gets imported via the script tag. But running mocha via the command line means it needs to be imported via node modules/requires.

Since this version of Blockly isn't module-friendly I'm not sure how to get the `mocha` command to work :/

File: appinventor/blocklyeditor/src/block_svg.js [hunk 1]
```diff
@@ -209,6 +228,10 @@ Blockly.BlockSvg.prototype.render = (function(func) {
 if (Blockly.Instrument.useRenderDown) {
 
 Blockly.BlockSvg.prototype.render = function(opt_bubble) {
+  if (this.isRendering) {
```
[the remark this answers is not in the document]
Comment (BeksOmega) [reply appinventor/blocklyeditor/src/block_svg.js]: @ewpatton I don't think option #2 is going to work. I forgot that it's not only going to affect methods on Block, but also a bunch of methods inside Input and Field. I was duplicating so much code that I just don't think it was going to be sustainable.

I'm gonna go ahead and wrap render in that try-finally you mentioned. If this problem is a deal breaker I'm cool with going back to the drawing board and implementing a renameCollapsed-esc function.

[the remark this answers is not in the document]
Comment (ewpatton) [reply appinventor/blocklyeditor/src/block_svg.js]: This is why I would rather that the internal functions not call render directly, but instead call something like our requestRender method. This way we can centrally track what state we are in and whether we need to do a render pass. Once many things start wanting to call render you can put them into this infinite loop if it isn't managed well (and it requires coordination across developers to make sure this stays true).

**Comment by BeksOmega** [comment]
Unit testing update: I was able to run the html file in a headless browser using [mocha-chrome](https://github.com/shellscape/mocha-chrome).  I also got it running in ant using [exec](https://ant.apache.org/manual/Tasks/exec.html). But it's not failing the build yet. I believe I can get the mocha-junit-reporter working using [this method](https://github.com/shellscape/mocha-chrome/issues/29#issuecomment-426244811) But so far mocha-junit hasn't been cooperating (mocha isn't finding the reporter at all). Still though, yay progress!

**Comment by BeksOmega** [comment]
Ok I have something that functions! You can view my changes (against this branch) [here](https://github.com/BeksOmega/appinventor-sources/compare/feat/update-collapsed-2...BeksOmega:unit-testing).

Tests1
Tests2
Tests3

Note: The junit tests are failing on master as well.

So how do you feel about it? Does this look like something you'd be willing to accept @ewpatton? If it is I have a few follow up questions about dependency handling and stuffs since I installed some things using npm.

**Comment by ewpatton** [comment]
@BeksOmega Did you install phantomjs, which is needed for the blocklyeditor tests? Can you update the PR with the mocha junit runner scaffolding?

File: appinventor/blocklyeditor/src/block_svg.js [hunk 2]
```diff
@@ -300,37 +373,11 @@ Blockly.BlockSvg.prototype.renderHere = function(opt_bubble) {
...
-      // Clear any warnings inherited from enclosed blocks.
-      this.setWarningText(null);
-    }
-    Blockly.BlockSvg.superClass_.setCollapsed.call(this, collapsed);
-
-    if (!renderList.length) {
-      // No child blocks, just render this block.
-      renderList[0] = this;
-    }
-    if (this.rendered) {
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/block_svg.js]: I'm concerned about the removal of this logic. In particular, we initialize blocks with this.rendered set to false because we don't want any render operations happening when we perform logic upgrades to the language. By removing this check, I think the blocks are being marked as rendered, and then loading blows up. To test, build this branch and then create a project with some blocks. Collapse the blocks and save the project. Reload App Inventor and you will get an error saying that the blocks workspace won't load. If you pause on caught exceptions in the debugger, you'll see that the bad block code is trying to do some operation even though the block isn't attached to the DOM yet.

**Comment by BeksOmega** [comment]
> @BeksOmega Did you install phantomjs, which is needed for the blocklyeditor tests?

Derp, that was the problem.

> Can you update the PR with the mocha junit runner scaffolding?

@ewpatton To clarify: does this mean you want me to merge/rebase my other branch into this one?

I can totally do that, but how would you prefer to handle dependencies (mocha, chai, and mocha-phantomjs)? Would you like me to set up a [package.json](https://docs.npmjs.com/creating-a-package-json-file) file? Or would you like me to try and add the source to the lib directory (all the dependencies are open source)?

File: appinventor/blocklyeditor/src/block_svg.js (hunk 2 above)
Comment (BeksOmega) [reply appinventor/blocklyeditor/src/block_svg.js]: @ewpatton Thanks for the detailed repro steps!

The fix was super easy, I just needed to check if the block was rendered before calling render.

But writing a test for this has been much trickier (and taken a lot longer). This bug only affects component blocks, so I'm having to mock the component database. I'll give it another shot tomorrow, but any advice would be appreciated.

File: appinventor/blocklyeditor/src/block_svg.js [hunk 3]
```diff
@@ -292,6 +327,44 @@ Blockly.BlockSvg.prototype.renderHere = function(opt_bubble) {
...
+  }
+
+  var text = this.toString(Blockly.COLLAPSE_CHARS);
+  var field = this.getField(collapsedFieldName);
+  if (field) {
+    field.setValue(text);
+    return;
+  }
+  var input = this.getInput(collapsedInputName) ||
+      this.appendDummyInput(collapsedInputName);
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/block_svg.js]: Another issue that previous fix uncovered:

blocks (40)

This is triggered by collapsing a block and reloading the project. During the initial render pass (we only call renderDown on top-level blocks), we get a double render. appendDummyInput adds a new input and immediately tries to render the block we are currently rendering (your this.isRendering check), but because we didn't call render() at the top that value is false when it should be true. Indirectly, that calls this method again, so we end up this input being prepopulated. The following line adds the second field.

Maybe it would make sense to move the isRendering check into renderHere rather than render.

**Comment by ewpatton** [comment]
@BeksOmega How big is the set of dependencies once you run `npm install`?

File: appinventor/blocklyeditor/src/block_svg.js (hunk 3 above)
Comment (BeksOmega) [reply appinventor/blocklyeditor/src/block_svg.js]: @ewpatton So what I ended up doing is reorganizing a bit. I changed `renderDown` and `renderHere` to private functions. This way render is the only access point (invariant). `render` handles all of the "should we render?" checks. The other functions handle all of the logic.

I'm definitely up for changing it, this just felt good to me. So please tell me what you think!

---

I also ended up having to remove renameCollapsed b/c it was causing problems with loading collapsed procedures. Everything seems to be working. I tested all relevant blocks, renaming the relevant parts, and loading from XML. But I will continue testing

**Comment by BeksOmega** [comment]
> How big is the set of dependencies once you run `npm install`?
```
AppInventor(unit-testing) * » du -sh node_modules
58M	node_modules
```
From looking at my [package-lock.json](https://pastebin.com/rn18jECD) most of the dependencies are from mocha.

[package-lock.json download](https://github.com/mit-cml/appinventor-sources/files/4361097/package-lock.zip)

**Comment by BeksOmega** [comment]
Just realized I forgot to @ewpatton again. Sorry :/ This should be ready for another look.
