### PR TITLE
replace all mappings and test code #3157

### LINKED ISSUE #3157: [iOS bug] yail/string-replace-mappings-longest-string
**Describe the bug**
image

**Steps to reproduce**

This bug happens when trying out our Therapist BOT on iphone. (https://appinventor.mit.edu/explore/resources/ai/therapist-bot)

### PR DESCRIPTION
**Pull request by cindyloo**
# Conflicts:
#	appinventor/components-ios/src/StringUtil.swift
#	appinventor/components-ios/tests/StringUtilTests.swift

General items:

- [ ] I have updated the relevant documentation files under docs/
- [x] My code follows the:
    - [ ] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [ ] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [x] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [x] I branched from `master` as both `master` and `ucr` are currently the same

What does this PR accomplish?

fixes #3157 

provide ios functionality for the `JavaStringUtils.java` replaceMappings component on Android

### CODE REVIEW

File: appinventor/components-ios/src/StringUtil.swift [hunk 1]
```diff
@@ -74,4 +74,122 @@ public func toString(_ object: Any?) -> String {
...
+        _ mappings: YailDictionary
+    ) -> String {
+        return replaceAllMappings(text, mappings: mappings, order: mappingOrderEarliestOccurrence)
+    }
+    
+    /// Main replacement method with custom ordering
+    public static func replaceAllMappings(
+        _ text: String,
+        mappings: YailDictionary,
+        order: MappingOrder
```
Comment (ewpatton) [inline appinventor/components-ios/src/StringUtil.swift:118]: Jenkins is complaining `MappingOrder` is not defined. Did you forget to add some files and changes to the project file?

Comment (cindyloo) [reply appinventor/components-ios/src/StringUtil.swift:118]: Looks like a merge kerfuffle as `MappingOrder` was committed at 5b14f7690c6b2fd4dd72cb0a326726127bac02e7. will add back in and test

**Comment by SusanRatiLane** [comment]
Feedback from testing: String comparison does not handle single quote and may not handle other characters that need to be escaped.

As an example app, I added common contractions to the TherapistBot (aka Eliza) so that it would respond correctly to more statements.
[TherapistBOT_Enhanced.aia.zip](https://github.com/user-attachments/files/23375257/TherapistBOT_Enhanced.aia.zip)

**Comment by SusanRatiLane** [comment]
The quote comparison failure turns out to be caused by the smart punctuation setting on the iPhone. Since this is default, iOS users are going to run into this problem with string comparisons using single quotes. It's a bigger issue than this PR, though, so it's out of scope.
