### PR TITLE
Show text validation errors if not in multiselect mode

### LINKED ISSUE #2130: Multiple select sometimes results in validation errors
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/multiple-object-selection-doesnt-work-since-update-183/6009?u=ewpatton): When picking components with properties that have validators, but the properties differ in value, the property editor is set to the empty string to signify the difference. This triggers the validator, which throws an error because empty string isn't a valid value. We should only run the validator when the change is done by the user, not programmatically to deal with the multiselect interaction.

**Affects**

- [x] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Errors should not occur when selecting multiple components. Validation errors should be brought to the user's attention (and reverted) if the user makes a change that no longer validates.

**Steps to reproduce**

The link above contains a video demonstrating the problem.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #2130 

Change-Id: Iadbfae002175a409b928f5c7e705c85cdb70566d

### CODE REVIEW

File: appinventor/appengine/src/com/google/appinventor/client/widgets/properties/PropertyEditor.java [hunk 1]
```diff
@@ -46,4 +48,12 @@ public void orphan() {
   public void refresh() {
     this.updateValue();
   }
+
+  public void setMultiselectMode(boolean multiselect) {
+    multiselectMode = true;
```
Comment (conorshipp) [inline appinventor/appengine/src/com/google/appinventor/client/widgets/properties/PropertyEditor.java:53]: @ewpatton I know this has been merged already but I noticed this and I'm curious to know whether or not this logic is intentional? Shouldn't it be `multiselectMode = multiselect`?
