### PR TITLE
Fix deprecation being inconsistent

### LINKED ISSUE #2216: Deprecation in components works inconsistently
**Describe the bug**

Each type of component feature (event, method, or property) reacts differently to deprecation.

Events: Nothing happens.
Methods: Marked as badBlock() and disabled.
Properties: Get a warning saying "Block is not defined. Delete this block!"

Deprecation

**Affects**
- [ ] Designer
- [X] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

I am assuming that methods are the only feature following the desired behavior. But I could be wrong.

**Steps to reproduce**

1. Open the Form component definition.
2. Deprecate `BackPressed`, `AskForPermission`, and both `AboutScreen` functions.
3. Load the attached (zipped) .aia
[test10.zip](https://github.com/mit-cml/appinventor-sources/files/4827569/test10.zip)

**Additional Info**

Events can be fixed by fixing [this line](https://github.com/mit-cml/appinventor-sources/blob/012a07bdef7ce1590af46c47ff27c83485c2191f/appinventor/blocklyeditor/src/blocks/components.js#L304). 
It should be:
```
    if (eventType && eventType.deprecated && this.workspace == Blockly.mainWorkspace) {
```
Not:
```
    if (eventType && eventType.deprecated === "true" && this.workspace === Blockly.mainWorkspace) {
```

Properties can be fixed by removing [this line](https://github.com/mit-cml/appinventor-sources/blob/012a07bdef7ce1590af46c47ff27c83485c2191f/appinventor/blocklyeditor/src/component_database.js#L337).

Happy to do this real quick if you guys agree methods have the correct behavior!

### PR DESCRIPTION
**Pull request by BeksOmega**
### Description

Resolves #2216 

Now all feature types correctly react like this:
Deprecation

### Testing
Could not replicate the behavior from #2216 

### Additional Info

Question: Why do we disable the blocks? The code gen should still work. There's also a problem that if you re-enable them there is no red "bad block" highlight:
Re-Enabled

### CODE REVIEW

**Comment by ewpatton** [comment]
@BeksOmega Generally when we deprecate something it is replaced with something else and we write an upgrader for it. It's usually pretty rare that something is outright deprecated with no replacement. In most cases, people shouldn't end up calling code that is deprecated in this way.

File: appinventor/blocklyeditor/src/blocks/components.js [hunk 1]
```diff
@@ -197,6 +197,20 @@ Blockly.ComponentBlock.addGenericOption = function(block, options) {
...
+/**
+ * Marks the passed block as a badBlock() and disables it if the data associated
+ * with the block is not defined, or the data is marked as deprecated.
+ * @param {Blockly.BlockSvg} block The block to check for deprecation.
+ * @param {EventDescriptor|MethodDescriptor|PropertyDescriptor} data The data
+ *     associated with the block which is possibly deprecated.
+ */
+Blockly.ComponentBlock.checkDeprecated = function(block, data) {
+  if ((!data || data.deprecated) && block.workspace == Blockly.mainWorkspace) {
+    block.badBlock();
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/blocks/components.js:209]: Setting the block to disabled overrides the visible effect of `badBlock`, so you could eliminate this call.

Comment (BeksOmega) [reply appinventor/blocklyeditor/src/blocks/components.js:209]: Yeah I thought it was weird that the behavior was to disabled blocks. Will fix :D

**Comment by ewpatton** [comment]
@BeksOmega LGTM, but I'll wait to merge until the badBlock issue is addressed.

**Comment by BeksOmega** [comment]
@ewpatton Done :D

**Comment by ewpatton** [comment]
@BeksOmega I was testing this but don't see the expected behavior. When I loaded test10 from the issue all of the blocks appear without any styling applied.

File: appinventor/blocklyeditor/src/blocks/components.js (hunk 1 above)
Comment (ewpatton) [reply appinventor/blocklyeditor/src/blocks/components.js:209]: I think we are mixing two different issues here. In the case where `data` is undefined, the block definition no longer exists. This is a truly `badBlock` and can't generate code because we don't have enough information to do so. In the case where the item is marked deprecated, the underlying code still exists and so we could disable the block (re-enabling will restore the old behavior) with the expectation that some day the block will go away. Alternatively, we could include an error message stating that the block is deprecated and should be removed. This mainly applies to extensions as if we do remove a block we usually have an upgrader to substitute in the replacement. Extensions don't have upgraders though so can't provide similar support.

**Comment by BeksOmega** [comment]
> @BeksOmega I was testing this but don't see the expected behavior. When I loaded test10 from the issue all of the blocks appear without any styling applied.

Huh I must not have tested it after I removed the setDisabled() call. It turns out the verify() call was unmarking them as bad, so the bad-block highlight wasn't showing up.

File: appinventor/blocklyeditor/src/blocks/components.js (hunk 1 above)
Comment (BeksOmega) [reply appinventor/blocklyeditor/src/blocks/components.js]: Ok I changed it so that if the functions `@Deprecated` the blocks are disabled. If the functions are removed, the blocks are marked as `badBlock`s.

So if you **deprecate** the functions for the blocks in the test aia, they look like this:
Deprecation

If you **remove** the functions, they look like this:
removed-blocks

**Review by ewpatton — APPROVED** [review]
LGTM
