### PR TITLE
Fix building apps with non-ASCII app names

### LINKED ISSUE #2542: Apps fail to compile when using non-ASCII characters in the app name
**Describe the bug**

[Forum reference](https://community.appinventor.mit.edu/t/aapt-execution-failed-in-my-app/39741?u=ewpatton): An app with non-ASCII characters in the AppName property of Screen1 fails to compile.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [ ] Companion
- [ ] Compiled apps
- [x] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Apps with non-ASCII characters in the name should compile successfully.

**Steps to reproduce**

An example app is included in the forum post.

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #2542 

It turns out that the Java Properties class will read/write using a different default charset depending on whether the method is called with an InputStream or a Reader. In the change I made that produces the project.properties file on the appengine server, I used a different version that produces UTF-8 compliant properties rather than the original ISO-8859-1 formatted. However, the build server was set up to read the ISO-8859-1 encoding. This updates the buildserver to also use UTF-8.

Change-Id: Idf2d133b1c3007a545af6a99c8e0b085bb9adb35

### CODE REVIEW

File: appinventor/buildserver/src/com/google/appinventor/buildserver/Project.java [hunk 1]
```diff
@@ -145,11 +146,8 @@ public Project(File file) {
 
       // Load project file
       properties = new Properties();
-      FileInputStream in = new FileInputStream(file);
-      try {
+      try (InputStreamReader in = new InputStreamReader(new FileInputStream(file))) {
         properties.load(in);
-      } finally {
-        in.close();
```
Comment (jisqyv) [inline appinventor/buildserver/src/com/google/appinventor/buildserver/Project.java:152]: @ewpatton You do not have to close the InputStreamReader (or the interior FIleInputStream)?

Comment (ewpatton) [reply appinventor/buildserver/src/com/google/appinventor/buildserver/Project.java:152]: This update makes use of a Java 1.7 feature called try-with-resources. When the try block is exited, the resources created in the parens after the try are automatically closed (even in the case of an exception). Effectively, it's just syntactic sugar that behaves the same as the old w.r.t. the finally block. The reader's close method will call the inner stream's close method.

**Review by jisqyv — APPROVED** [review]
LGTM
