### PR TITLE
Changed TextSize property to FontSize, fixes: #3389

### LINKED ISSUE #3389: ListView text size property names need to match other properties
In ListView, many layouts have two fields -- MainText and DetailText. Most properties that are separate follow the pattern, [Name] and [Name]Detail, e.g. TextColor and TextColorDetail. Text size property is TextSize and FontSizeDetail, which makes it confusing to deal with.

These properties need to be named to match the format of the others. The name change is simple by itself, but but it will need to branch from ucr, have a property upgrader, and change references in both Android and iOS companions.

### PR DESCRIPTION
**Pull request by patryk84a**
General items:

- [ ] I have updated the relevant documentation files under docs/
- [x] My code follows the:
    - [x] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [x] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [ ] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [x] I branched from `ucr`
- [x] My pull request has `ucr` as the base

Further, if you've changed the blocks language or another user-facing designer/blocks API (added a SimpleProperty, etc.):

- [x] I have updated the corresponding version number in appinventor/components/src/.../common/YaVersion.java
- [x] I have updated the corresponding upgrader in appinventor/appengine/src/.../client/youngandroid/YoungAndroidFormUpgrader.java (components only)
- [x] I have updated the corresponding entries in appinventor/blocklyeditor/src/versioning.js

Fixes #3389 .

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

File: appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockListView.java [hunk 1]
```diff
@@ -293,7 +293,7 @@ private void createImageTwoTextLayout(JSONObject object) {
   }
 
   private void setItemHeight(boolean detail, boolean image) {
-    int mainHeight = Integer.parseInt(mainFontSize);
+    int mainHeight = (int) Float.parseFloat(mainFontSize);
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/editor/simple/components/MockListView.java:296]: This is a niggle, but if we need an integer for the the height of the text item, it seems better to use Math.Ceil(). That is the math method that rounds a float up to the next larger int. The int cast just chops of the decimal, so we'd end up with a text item height smaller than the font height.

DetailHeight already uses the casting method, so it seems to work reasonably the way it is.

**Review by SusanRatiLane — APPROVED** [review]
This tests out, including the project upgrade.

File: appinventor/components/src/com/google/appinventor/components/runtime/ListView.java [hunk 2]
```diff
@@ -651,56 +651,24 @@ public void TextColorDetail(int argb) {
...
-   * Returns the listview's text font Size
-   *
-   * This property is provided for backwards compatibility
-   * it takes and returns an integer, but in reality it just
-   * updates the FontSize property, which works with floats
-   *
-   * @return text size as an integer
-   */
-  @SimpleProperty(description = "The text size of the listview items.",
-      category = PropertyCategory.APPEARANCE)
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/ListView.java:663]: Mark the old versions as `@Deprecated` but leave the code on the off chance they're called by extensions.

**Review by ewpatton — APPROVED** [review]
