### PR TITLE
Fix #3335: Detect and handle unavailable extensions in dragged PNGs

### LINKED ISSUE #3335: Detect unavailable extensions in dragged PNGs
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/drag-and-drop-of-blocks-as-png-doesnt-work/137126): If a PNG file containing blocks from an extension is dragged into a project that doesn't contain that extension, mayhem ensues.

**Affects**

- [ ] Designer
- [x] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Given that the project doesn't contain the extension, we should probably show an error of some kind and refuse to instantiate the blocks.

**Steps to reproduce**

1. Create a project and import an extension such as the BLE extension.
2. Create a block stack and export it to a single PNG by right clicking on the block and selecting Download Blocks as PNG
3. Create a new project
4. Drag the PNG from step 2 into the block workspace of the project created in step 3

### PR DESCRIPTION
**Pull request by d1vyanshu-kumar**
General items:

- [x] My code follows the:
    - [x] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [x] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [x] `ant tests` passes on my machine

If your code changes how something works on the device (i.e., it affects the companion):

- [x] I branched from `master`
- [x] My pull request has `master` as the base

For all other changes:

- [x] I branched from `master`
- [x] My pull request has `master` as the base

What does this PR accomplish?

**-** To solve the issue of importing blocks from a PNG file that requires extensions not present in the project, I added the following steps:  

**1.** **Extract Block Types**: created a function extractBlockTypes to extract the block types from the XML data embedded in the PNG file.
**2.** **Validate Block Types**: created a function validateBlockTypes to check if the extracted block types are available in the component database of the workspace.
**3. Show Missing Extensions Dialog:** created a function showMissingExtensionDialog to display an alert dialog listing the missing extensions if any.
**4. Modify importPngAsBlock:** modified the importPngAsBlock function to:

- Extract block types from the XML.
- Validate the block types against the component database.
- Show an error dialog and abort the import if any required extensions are missing.

Fixes #3335

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by d1vyanshu-kumar** [comment]
https://github.com/user-attachments/assets/e3edbaa6-e59b-4384-b65e-4c23307aa931

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

File: appinventor/blocklyeditor/src/exportBlocksImage.js [hunk 1]
```diff
@@ -529,6 +598,18 @@ Blockly.importPngAsBlock = function(workspace, xy, png) {
     if (xmlChunk) {
       var xmlText = new TextDecoder().decode(xmlChunk.data);
       var xml = /** @type {!Element} */ (Blockly.utils.xml.textToDom(xmlText));
+      if (!xml) {
+        console.error('Failed to parse XML from PNG.');
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/exportBlocksImage.js:602]: Is there a reason we aren't showing this error to the user as well?

File: appinventor/blocklyeditor/src/exportBlocksImage.js [hunk 2]
```diff
@@ -517,6 +517,75 @@ Blockly.exportBlockAsPng = function(block) {
...
+ * @param {Array<string>} missingExtensions - The missing component types.
+ */
+function showMissingExtensionDialog(missingExtensions) {
+  // Filter out undefined or null values
+  missingExtensions = missingExtensions.filter(function(extension) {
+    return extension !== undefined && extension !== null;
+  });
+
+  if (missingExtensions.length > 0) {
+    var message = 'This image references the following blocks which require extensions that are not present in the project:\n\n';
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/exportBlocksImage.js:583]: This should either be added to the Blockly.Msg object and a corresponding entry in the translation file, or we should add it to OdeMessages.java and figure out how to get it here so that it can be translated into the user's language.

File: appinventor/blocklyeditor/src/exportBlocksImage.js [hunk 3]
```diff
@@ -517,6 +517,75 @@ Blockly.exportBlockAsPng = function(block) {
...
+
+/**
+ * Validates the block types against the component database in the workspace.
+ * @param {Array<string>} blockTypes - The block types to validate.
+ * @param {Blockly.WorkspaceSvg} workspace - The workspace containing the component database.
+ * @returns {Array<string>} An array of missing component types.
+ */
+function validateBlockTypes(blockTypes, workspace) {
+  if (!blockTypes || blockTypes.length === 0) {
+    console.warn('No block types provided for validation.');
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/exportBlocksImage.js:548]: I don't think a warning is necessary here. It's logical that the empty set of block types is valid.

File: appinventor/blocklyeditor/src/exportBlocksImage.js [hunk 4]
```diff
@@ -517,6 +517,75 @@ Blockly.exportBlockAsPng = function(block) {
...
+    return [];
+  }
+
+  var componentDb = workspace.getComponentDatabase();
+  if (!componentDb) {
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/exportBlocksImage.js:553]: Note that the component database is allocated during the setup of the workspace, so this should never be true.

File: appinventor/blocklyeditor/src/exportBlocksImage.js [hunk 5]
```diff
@@ -517,6 +517,75 @@ Blockly.exportBlockAsPng = function(block) {
...
+/**
+ * Extracts the block types from the given XML.
+ * @param {Document} xml - The XML document containing blocks.
+ * @returns {Array<string>} An array of block types.
+ */
+function extractBlockTypes(xml) {
+  var blockTypes = [];
+  var blocks = xml.getElementsByTagName('block');
+  for (var i = 0; i < blocks.length; i++) {
+    var mutation = blocks[i].getElementsByTagName('mutation')[0];
```
Comment (ewpatton) [inline appinventor/blocklyeditor/src/exportBlocksImage.js:529]: Note that `getElementsByTagName` gets all descendants, so you could just do `xml.getElementsByTagName('mutation')` to get all of the mutations. Otherwise, this code ends up being quadratic in its runtime since for each block you may be looking up mutations on its children, grandchildren, etc. not just its own mutation.

File: appinventor/blocklyeditor/src/exportBlocksImage.js (hunk 1 above)
Comment (d1vyanshu-kumar) [reply appinventor/blocklyeditor/src/exportBlocksImage.js:602]: No, there is no particular reason. At that moment, I didn't think about notifying the user. I will add an `alert `to inform the user about the error.

File: appinventor/blocklyeditor/src/exportBlocksImage.js (hunk 4 above)
Comment (d1vyanshu-kumar) [reply appinventor/blocklyeditor/src/exportBlocksImage.js:553]: ok. I will remove this statement

File: appinventor/blocklyeditor/src/exportBlocksImage.js (hunk 3 above)
Comment (d1vyanshu-kumar) [reply appinventor/blocklyeditor/src/exportBlocksImage.js:548]: I will remove this warning.

**Comment by d1vyanshu-kumar** [comment]
Hi @ewpatton,

Thank you so much for reviewing my PR. I'll make the requested changes and submit an updated PR soon.

**Comment by d1vyanshu-kumar** [comment]
@ewpatton I have made the requested changes. Please review and let me know if anything else is needed.

**Review by ewpatton — APPROVED** [review]
LGTM
