### PR TITLE
Have Bluetooth components ask for permissions on Android 12+

### LINKED ISSUE #2740: Need to ask for Android 12 dangerous Bluetooth permissions
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/bluetooth-conection-problem-fail-message-in-the-browser/66107?u=ewpatton): When using blocks like Connect on Android 12, we must first ask for user permission for BLUETOOTH_* permissions. As a workaround, people can go into the settings app and grant permission that way.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

When a Bluetooth request is made to scan, connect, or advertise, permission must be asked of the user on Android 12+.

**Steps to reproduce**

1. Create a simple bluetooth app on Android 12. Using any of the connection blocks will fail with a permission error.

### PR DESCRIPTION
**Pull request by ewpatton**
Resolves #2740 

Note that this PR is built on top of #2749 and #2754. Only the latest commit needs to be reviewed once those PRs are merged. Since this also adds a new property, I merged master to pick up #2743 as well so the versioning is correct.

### CODE REVIEW

File: appinventor/components/src/com/google/appinventor/components/runtime/util/SUtil.java [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+  public static boolean requestPermissionsForS(String[] sdk31Permissions, Form form,
+      Component source, String caller, PermissionResultHandler continuation) {
+    List<String> permsNeeded = new ArrayList<>();
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+      Collections.addAll(permsNeeded, sdk31Permissions);
+    } else {
+      permsNeeded.add(BLUETOOTH);
+      permsNeeded.add(BLUETOOTH_ADMIN);
+    }
+    return performRequest(form, source, caller, permsNeeded, continuation);
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/util/SUtil.java:139]: As I'm working on the BLE extension I'm not 100% sure this logic is correct and I may need to come back to it.

File: appinventor/components/src/com/google/appinventor/components/common/YaVersion.java [hunk 2]
```diff
@@ -756,8 +758,10 @@ private YaVersion() {
   // - The BluetoothClient.Secure property was added.
   // For BLUETOOTHCLIENT_COMPONENT_VERSION 6:
   // - The BluetoothClient.DisconnectOnError property was added.
-  // For BLUETOOTH_CLIENT_COMPONENT_VERSION 7:
-  // - The BluuetoothClient.PollingRate property was added.
+  // For BLUETOOTHCLIENT_COMPONENT_VERSION 7:
+  // - The BluetoothClient.PollingRate property was added.
+  // For BLUETOOTHCLIENT_COMPONENT_VERSION 8:
+  // - The BluetoothClient.NoLocationNeeded property was added.
   public static final int BLUETOOTHCLIENT_COMPONENT_VERSION = 7;
```
Comment (jisqyv) [inline appinventor/components/src/com/google/appinventor/components/common/YaVersion.java:765]: Oops, forgot to increment this to 8!
Don't worry, I caught and fixed this during the merge (had a conflict to deal with)

**Review by jisqyv — APPROVED** [review]
LGTM (I'm going to force push a commit with merge conflicts resolved)
