### PR TITLE
Trash refactor

### LINKED ISSUE #3222: When empty folders are sent to trash, they are not removed from the project list
**Describe the bug**

When empty folders are selected on the project explorer and sent to trash, they still appear in the project list when the page is reloaded.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [X] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

Empty folders should be deleted. Currently, folders can't be restored from trash, though more sophisticated folder-trash handling could be a feature in the future.

### PR DESCRIPTION
**Pull request by SusanRatiLane**
General items:

- [ ] I have updated the relevant documentation files under docs/
- [X] My code follows the:
    - [X] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [ ] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [ ] `ant tests` passes on my machine

For all other changes:

- [X] I branched from `master`
- [X] My pull request has `master` as the base

What does this PR accomplish?

Previously, the trash can only accepted projects, and it was impossible to delete folders. This change refactors the trash/restore/delete system to behave more like the trash system from an OS. Project can be moved to trash individually, and folders can be trashed with their nested contents of projects and folders. All of these things can be restored or deleted permanently

Fixes #3222

### CODE REVIEW

File: appinventor/appengine/src/com/google/appinventor/client/actions/RestoreProjectAction.java [hunk 1]
```diff
@@ -22,10 +23,11 @@ public void execute() {
     if (Ode.getInstance().getCurrentView() == Ode.TRASHCAN) {
       List<Project> selectedProjects = ProjectListBox.getProjectListBox().getProjectList()
                                            .getSelectedProjects();
-      if (selectedProjects.size() > 0) {
-        for (Project project : selectedProjects) {
-          project.restoreFromTrash();
-        }
+      List<ProjectFolder> selectedFolders = ProjectListBox.getProjectListBox().getProjectList()
+                                                .getSelectedFolders();
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/actions/RestoreProjectAction.java:27]: Indentation should just be +4 here.

File: appinventor/appengine/src/com/google/appinventor/client/actions/RestoreProjectAction.java [hunk 2]
```diff
@@ -22,10 +23,11 @@ public void execute() {
...
+      if (!selectedProjects.isEmpty() || !selectedFolders.isEmpty()) {
+        Ode.getInstance().getFolderManager().moveItemsToFolder(selectedProjects, selectedFolders,
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/actions/RestoreProjectAction.java:29]: You could cache the call to Ode.getInstance() and reuse it.

File: appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.java [hunk 3]
```diff
@@ -71,15 +78,15 @@ public void onBlur(BlurEvent event) {
...
-      if (!"*trash*".equals(child.getName())) {
-        FolderTreeItem childItem = renderFolder(child);
-        childItem.setState(true);
-        treeItem.addItem(childItem);
+      for (ProjectFolder child : folder.getChildFolders()) {
+        if (!"*trash*".equals(child.getName()) && !selectedFolders.contains(child)) {
+          FolderTreeItem childItem = renderFolder(child);
+          childItem.setState(true);
+          treeItem.addItem(childItem);
+        }
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/wizards/MoveProjectsWizard.java:88]: Why was the indentation changed here?

File: appinventor/appengine/src/com/google/appinventor/client/actions/DeleteAction.java [hunk 4]
```diff
@@ -25,33 +25,32 @@ public void execute() {
...
             // error.
             ErrorReporter.reportInfo(MESSAGES.noProjectSelectedForDelete());
           }
         } else { //We are deleting a project in the designer view
-          List<Project> selectedProjects = new ArrayList<Project>();
+          List<Project> selectedProjects = new ArrayList<>();
           Project currentProject = Ode.getInstance().getProjectManager().getProject(Ode.getInstance().getCurrentYoungAndroidProjectId());
           selectedProjects.add(currentProject);
-          if (deleteConfirmation(selectedProjects)) {
+          if (deleteConfirmation(true, selectedProjects, new ArrayList<>())) {
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/actions/DeleteAction.java:53]: It might be better to use `Collections.emptyList()` if GWT supports it in order to not have to result a new list every time this gets called.

**Review by ewpatton — CHANGES_REQUESTED** [review]
A few minor things.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java [hunk 5]
```diff
@@ -87,10 +87,10 @@ public ProjectList() {
     bindIU();
     setIsTrash(false);
     refreshSortIndicators();
-    Ode.getInstance().getFolderManager().addFolderManagerEventListener(this);
+//    Ode.getInstance().getFolderManager().addFolderManagerEventListener(this);
 
     // It is important to listen to project manager events as soon as possible.
-    Ode.getInstance().getProjectManager().addProjectManagerEventListener(this);
+//    Ode.getInstance().getProjectManager().addProjectManagerEventListener(this);
```
[the remark this answers is not in the document]
Comment (SusanRatiLane) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java:93]: > Are we sure commenting these out is the correct thing to be doing?

They looked redundant to me (I'd have to reconstruct why), but it was hard to prove. This is one of the reasons I solicited power user testing.

It doesn't seem that removing these lines affected behavior.

[the remark this answers is not in the document]
Comment (SusanRatiLane) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/youngandroid/ProjectList.java:93]: > Are we sure commenting these out is the correct thing to be doing?

Actually, the "why" seems to be that they are also added in bindUI(). I assume they were moved there in the UI refactor, but maybe added back to the old location in a merge?

File: appinventor/appengine/src/com/google/appinventor/client/actions/DeleteAction.java [hunk 6]
```diff
@@ -6,18 +6,20 @@
...
 import com.google.appinventor.client.explorer.folder.ProjectFolder;
 import com.google.appinventor.client.explorer.project.Project;
 import com.google.gwt.user.client.Command;
 import com.google.gwt.user.client.Window;
+
 import java.util.ArrayList;
+import java.util.Collections;
 import java.util.List;
 
+import static com.google.appinventor.client.Ode.MESSAGES;
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/actions/DeleteAction.java:21]: It's possible my rule file is broken, but this should not have moved.

File: appinventor/appengine/src/com/google/appinventor/client/actions/DeleteForeverProjectAction.java [hunk 7]
```diff
@@ -19,6 +17,8 @@
 import java.util.ArrayList;
 import java.util.List;
 
+import static com.google.appinventor.client.Ode.MESSAGES;
```
Comment (ewpatton) [inline appinventor/appengine/src/com/google/appinventor/client/actions/DeleteForeverProjectAction.java:20]: Ditto.

**Review by ewpatton — CHANGES_REQUESTED** [review]
Two minor issues with import ordering otherwise LGTM.

**Review by ewpatton — APPROVED** [review]
