### PR TITLE
Fixes Type name to delete project/screen

### LINKED ISSUE #2071: Type name to delete project/screen
**Describe the desired feature**

Rather than simply having a delete and cancel button to delete a screen or project (which is not undoable), instead prompt the person to type in the exact name of the thing to confirm deletion. Don't activate the button until the string is typed.

**Give an example of how this feature would be used**

This is intended to prevent accidental deletion of screens and projects, which cannot be undone.

**Why doesn't the current App Inventor system address this use case?**

The current system only asks the user to confirm with a single click or press of the enter key. Since we cannot undo this step, we should increase the barrier to deleting a screen or project (project deletion is alleviated somewhat with the addition of the trash project list).

**Why is this feature beneficial to App Inventor's educational mission?**

It will prevent students from accidentally deleting a significant amount of work in some instances. Since we can't recover screens it further increases the barrier to a bad outcome.

### PR DESCRIPTION
**Pull request by beinganonymous**
- [ ] My code follows the:
    - [x] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
- [x] `ant tests` passes on my machine

For all other changes:

- [x] I branched from `master`
- [x] My pull request has `master` as the base

What does this PR accomplish?

I have added ``Type name to delete screen`` feature, where user have to type accurate screen name to delete screen to avoid accidental deletion. Also this PR automatically allows user to save current checkpoint while deleting screen.

Fixes #2071  .

app

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

**Comment by pavi2410** [comment]
@AppInventorWorkerBee ok to test

**Comment by SusanRatiLane** [comment]
From testing: 

The Remove Screen probably shouldn't prepopulate with any screen name, even Screen1. 
Screen Shot 2020-03-23 at 4 02 51 PM

When you click OK with a screen name that doesn't match, there is no response at all. There should probably be a notification to the user stating why the delete did not go through.

**Comment by ewpatton** [comment]
@SusanRatiLane @beinganonymous I would suggest having a KeyUp handler that validates by coloring the textbox red or not (this is what GitHub does to delete a repo). We should also have text at the beginning to the effect of:

"Warning: You are deleting a screen. This operation cannot be undone. Please type the name of the screen ({0}) into the box below to confirm you really want to do this."

**Comment by ewpatton** [comment]
Possibly also change the checkbox text to "Create checkpoint before deleting"

**Comment by SusanRatiLane** [comment]
> @SusanRatiLane @beinganonymous I would suggest having a KeyUp handler that validates by coloring the textbox red or not (this is what GitHub does to delete a repo). We should also have text at the beginning to the effect of:
> 
> "Warning: You are deleting a screen. This operation cannot be undone. Please type the name of the screen ({0}) into the box below to confirm you really want to do this."

This warning currently appears when OK is clicked with a match as a final "Are you sure?" confirmation.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 1]
```diff
@@ -36,6 +69,195 @@ public boolean willCallExecuteNextCommand() {
...
+
+          if (formName.startsWith(prefix)) {
+            try {
+              highIndex = Math.max(highIndex, Integer.parseInt(formName.substring(prefixLength)));
+            } catch (NumberFormatException e) {
+              continue;
+            }
+          }
+        }
+      }*/
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: If this is the final version, please remove commented code.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 2]
```diff
@@ -36,6 +69,195 @@ public boolean willCallExecuteNextCommand() {
...
+      String defaultFormName = prefix + (highIndex + 1);
+
+      newNameTextBox = new LabeledTextBox(MESSAGES.formNameLabel());
+      newNameTextBox.setText(defaultFormName);
+      newNameTextBox.getTextBox().addKeyUpHandler(new KeyUpHandler() {
+        @Override
+        public void onKeyUp(KeyUpEvent event) {
+          int keyCode = event.getNativeKeyCode();
+          if (keyCode == KeyCodes.KEY_ENTER) {
+            //handleOkClick(projectRootNode);
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Is there a reason we're checking for the enter key here? The click call is commented out.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 3]
```diff
@@ -36,6 +69,195 @@ public boolean willCallExecuteNextCommand() {
...
+        HTML tooManyScreensLabel = new HTML(MESSAGES.formCountErrorLabel());
+        errorPanel.add(tooManyScreensLabel);
+        errorPanel.setSize("100%", "24px");
+        contentPanel.add(errorPanel);
+
+        okText = MESSAGES.addScreenButton();
+        cancelText = MESSAGES.cancelScreenButton();
+
+        // okText = "Add";
+        // cancelText = "Don't Add";
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Commented code.

**Comment by ewpatton** [comment]
> > @SusanRatiLane @beinganonymous I would suggest having a KeyUp handler that validates by coloring the textbox red or not (this is what GitHub does to delete a repo). We should also have text at the beginning to the effect of:
> > "Warning: You are deleting a screen. This operation cannot be undone. Please type the name of the screen ({0}) into the box below to confirm you really want to do this."
> 
> This warning currently appears when OK is clicked with a match as a final "Are you sure?" confirmation.

The text I wrote included instructions for how to use the form. I'm not sure that it is obvious to most why you would need to type a screen name in. "After all, the app already knows what screen I am on." And "why do I have to type the current screen name versus the one I want to delete" (which may not be the current one).

Also, why does the textbox prepopulate with Screen1? Screen1 can never be removed. The text should be blank.

The error message that appears after you click OK is the one that appears in prod to confirm deletion. It might be worth keeping as one last failsafe, but otherwise it could probably go after this feature is merged as it is meant to be more of a confirmation than just clicking OK.

**Comment by beinganonymous** [comment]
> @SusanRatiLane @beinganonymous I would suggest having a KeyUp handler that validates by coloring the textbox red or not (this is what GitHub does to delete a repo). We should also have text at the beginning to the effect of:
> 
> "Warning: You are deleting a screen. This operation cannot be undone. Please type the name of the screen ({0}) into the box below to confirm you really want to do this."

@ewpatton Should i add feature like if user types wrong screen name then textbox should be red or if user types right screen name then textbox should be green ?

**Comment by ewpatton** [comment]
@beinganonymous I think red versus normal is sufficient for this. Because the operation is destructive, I don't think we want to use green at all if possible. Like I've previously said, I think how GitHub does this for repo deletion is a good model of how it should look/behave.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 1 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Removed Commented Code

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 2 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Removed KeyUp Handler

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 3 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Removed Commented Code

**Comment by beinganonymous** [comment]
@ewpatton @SusanRatiLane I have implemented requested changes in above commits.
 - [x] The Remove Screen won't prepopulate with any screen name.
 - [x] If screen name doesn't match then notification to the user will be given. 
 - [x] Added KeyUp handler where TextBox Border turns into red color if text matches with Screen Name.
 - [x] Added Warning Message to the Dialog Box.
 - [x] Removed Commented Code.
 - [x] Changed the checkbox text to "Create checkpoint before deleting"

File: appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java [hunk 4]
```diff
@@ -117,6 +117,10 @@
   @DefaultMessage("Checkpoint ...")
   @Description("Label of the button for checkpoint")
   String checkpointButton();
+  
+  @DefaultMessage("Create checkpoint before deleting"")
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java]: I had a compile fail probably caused by the quotes typo here.

Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java]: Resolved the quotes typo

Comment (SusanRatiLane) [reply appinventor/appengine/src/com/google/appinventor/client/OdeMessages.java]: It looks like there are now merge conflicts in the PR.

**Comment by beinganonymous** [comment]
Resolved all Merge Conflicts

**Comment by SusanRatiLane** [comment]
This is what I see when I type a form name that doesn't match. The top-screen message asks the user to "select" a valid screen name, and nothing turns red.

You did show the error at the top in your video demo, but I didn't even notice it. It's not really where you think to look. If we're going to have an error message, it should say, "Please type a valid screen name," but I'm not sure we need the error message at all. The field border turning red should be enough.

Screen Shot 2020-03-26 at 9 54 34 AM

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 5]
```diff
@@ -36,6 +70,158 @@ public boolean willCallExecuteNextCommand() {
...
+   * Shows a confirmation dialog.
+   *
+   * @return {@code true} if the delete file command should be executed or
+   *         {@code false} if it should be canceled
+   */
+  protected boolean deleteConfirmation() {
+    return Window.confirm(MESSAGES.reallyDeleteFile());
+  }
+  
+  private class NewFormDialog extends DialogBox {
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: This class should have a more meaningful name. We're deleting a form, not adding one.

**Comment by beinganonymous** [comment]
@SusanRatiLane Updated following changes
 - [x] TextBox border will turn red if screen name is wrong.
 - [x] Classname NewFormDialog changed to DeleteFormDialog.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 6]
```diff
@@ -36,6 +70,158 @@ public boolean willCallExecuteNextCommand() {
...
   public void execute(final ProjectNode node) {
+	  if (node instanceof YoungAndroidSourceNode) {
+  		new DeleteFormDialog((YoungAndroidSourceNode) node).center();
+  		
+	  } 
+	  else {
+  		  executionFailedOrCanceled();
+  		  throw new IllegalArgumentException("node must be a YoungAndroidProjectNode");
+	  }
+  }
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Strange whitespace here. Our style guide calls for two spaces for each of these indents.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 7]
```diff
@@ -36,6 +70,158 @@ public boolean willCallExecuteNextCommand() {
...
+   *         {@code false} if it should be canceled
+   */
+  protected boolean deleteConfirmation() {
+    return Window.confirm(MESSAGES.reallyDeleteFile());
+  }
+  
+  private class DeleteFormDialog extends DialogBox {
+    // UI elements
+    private final LabeledTextBox newNameTextBox;
+	private final CheckBox cb = new CheckBox(MESSAGES.checkBoxButton());
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Extra space here.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 8]
```diff
@@ -36,6 +70,158 @@ public boolean willCallExecuteNextCommand() {
...
+      cb.setValue(true);
+      final Button okButton = new Button(okText);
+      okButton.addClickHandler(new ClickHandler() {
+        @Override
+        public void onClick(ClickEvent event) {
+    	   handleOkClick(projectRootNode);    
+        }
+      });
+   
+      if (projectRootNode instanceof YoungAndroidFormNode) {
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Whitespace here needs to be two spaces per indent.

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 6 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Removed whitespace

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 7 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Removed extra space

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java (hunk 8 above)
Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Added two whitespace per indent

File: appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java [hunk 9]
```diff
@@ -144,40 +143,38 @@ public void onClick(ClickEvent event) {
...
-	  }
-
+        final String abc1 = ((YoungAndroidFormNode) projectRootNode).getFormName();
+        HorizontalPanel labelPanel = new HorizontalPanel();
+        Label warnmsg = new Label(MESSAGES.reallyDeleteWarning(abc1));
+  	labelPanel.add(warnmsg);
+  	labelPanel.setSize("100%", "22px");
+  	contentPanel.add(labelPanel);
+  	contentPanel.add(newNameTextBox);
+        HorizontalPanel buttonPanel = new HorizontalPanel();
```
Comment (SusanRatiLane) [inline appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Hmm. The whitespace here is still weird. Are you using tab key for spacing? You're probably better off using spaces instead.

Comment (beinganonymous) [reply appinventor/appengine/src/com/google/appinventor/client/explorer/commands/DeleteFileCommand.java]: Sorry actually i was using tab key instead of spaces, i will keep it in the mind to use spaces instead.
Removed all weird whitespaces
