### PR TITLE
Fix procedure names in backpack

### LINKED ISSUE #3388: Procedures copied to backpack are renamed "procedure"
When a named procedure block is dragged to the backpack, its name changes to "procedure".

**Affects**

- [ ] Designer
- [X] Blocks editor
- [ ] Projects Explorer
- [ ] Companion
- [ ] Compiled apps
- [ ] Buildserver
- [ ] Debugging
- [ ] Other... (please describe)

**Expected behavior**

The procedure block should retain its original name

### PR DESCRIPTION
**Pull request by ewpatton**
Change-Id: Icfbcb7df332ad8d087f5098600413cff4fb4e5df

General items:

- [ ] I have updated the relevant documentation files under docs/
- [x] My code follows the:
    - [ ] [Google Java style guide](https://google.github.io/styleguide/javaguide.html) (for .java files)
    - [x] [Google JavaScript style guide](https://google.github.io/styleguide/jsguide.html) (for .js files)
- [x] `ant tests` passes on my machine

For all other changes:

- [x] I branched from `master`
- [x] My pull request has `master` as the base

What does this PR accomplish?

Fixes #3388

### CODE REVIEW

**Comment by ewpatton** [comment]
@mark-friedman Note that this version of the lexvar plugin is built from my PR in that repo.

File: appinventor/blocklyeditor/src/workspace_svg.js [hunk 1]
```diff
@@ -237,6 +237,7 @@ Blockly.WorkspaceSvg.prototype.addBackpack = function() {
         scrollbars: true,
         media: './assets/',
         disabledPatternId: this.options.disabledPatternId,
+        renderer: 'geras2_renderer',
```
Comment (mark-friedman) [inline appinventor/blocklyeditor/src/workspace_svg.js:240]: What was the issue here?

**Review by mark-friedman — APPROVED** [review]
LGTM

File: appinventor/blocklyeditor/src/workspace_svg.js (hunk 1 above)
Comment (ewpatton) [reply appinventor/blocklyeditor/src/workspace_svg.js:240]: The geras2_renderer provides the indented input rendering, so blocks with indented inputs (procedures or local scope blocks returning values) would render as regular right-aligned inputs.

Comment (mark-friedman) [reply appinventor/blocklyeditor/src/workspace_svg.js:240]: Ah, good catch!
