### PR TITLE
Fix dictionary issues with String/FString mismatch

### LINKED ISSUE #2023: Dictionaries lookups fail when using joined strings
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/remove-entry-for-key-doesnt-work/3334/4?u=ewpatton): Removing the key "key3" works fine, but using the key `join("key", 3)` does not. This is because HashMap evaluates the equality of the two elements, and since String("key3") != FString("key3") (Kawa's String type), the removal fails.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

Removing the key should work regardless of whether it is a String or FString passed in. We should normalize to String.

**Steps to reproduce**

1. Create a dictionary
2. Call the remove entry block but pass a key composed using the join block
3. Check the size of the dictionary and observe that it hasn't changed

### LINKED ISSUE #2024: List by walking key path does not work in a loop
**Describe the bug**

[From the forum](https://community.appinventor.mit.edu/t/list-by-walking-key-path-in-for-loop-doesnt-work/3322?u=ewpatton): The list by walking key path block does not appear to work when placed in a lop.

**Affects**

- [ ] Designer
- [ ] Blocks editor
- [x] Companion
- [x] Compiled apps
- [ ] Buildserver
- [ ] Other... (please describe)

**Expected behavior**

The block should work as intended whether it is placed in a loop or not.

**Steps to reproduce**

1. Create a list containing some dictionaries
2. Create a loop over the length of the list
3. Construct a key path that includes the index and a walk all at level block
4. Run the code and see that nothing happens

### PR DESCRIPTION
**Pull request by ewpatton**
Fixes #2023 
Fixes #2024 

Change-Id: If4549950bac9bd0aa35efdb7f5f77f70242cfe38

### CODE REVIEW

File: appinventor/blocklyeditor/src/generators/yail.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ Blockly.Yail.YAIL_CLOSE_BLOCK = ")\n";
 Blockly.Yail.YAIL_COMMENT_MAJOR = ";;; ";
 Blockly.Yail.YAIL_COMPONENT_REMOVE = "(remove-component ";
 Blockly.Yail.YAIL_COMPONENT_TYPE = "component";
-Blockly.Yail.YAIL_CONSTANT_ALL = 'com.google.appinventor.components.runtime.util.YailDictionary:ALL';
+Blockly.Yail.YAIL_CONSTANT_ALL = '(static-field com.google.appinventor.components.runtime.util.YailDictionary \'ALL)';
```
Comment (pavi2410) [inline appinventor/blocklyeditor/src/generators/yail.js]: Should use double quotes here to get rid of escaping the single quote

Comment (ewpatton) [reply appinventor/blocklyeditor/src/generators/yail.js]: Since we're trying to follow the [Google style guides](https://google.github.io/styleguide/jsguide.html#features-string-literals), string literals are supposed to be single quoted, not double quoted (I realize that most of the file isn't actually following that convention at the moment). Note that the style guide recommends using a template string in this case, but because we are targeting ES5 that's not an available feature. I'm going to recommend that we stick with the single quotes for now. As we make updates to the sources we can migrate code to match the style guide as needed.
