### PR TITLE
Used BluetoothSocket.isConnected on devices with APILevel >=14

### LINKED ISSUE #868: Consider using BluetoothSocket.isConnected on phone with API >= 14
There is some confusion on the forum regarding the BluetoothClient.IsConnected method since it will only return false when the connection status is reset, which will only occur if one attempts to read/write the broken socket. For devices with an API level of 14 (ice cream sandwich) or higher, we can use the `isConnected()` method of BluetoothSocket to report a more accurate connection status without requiring developers to perform an operation on the socket.

### PR DESCRIPTION
**Pull request by ellelili2025**
Fixes #868

### CODE REVIEW

File: appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java [hunk 1]
```diff
@@ -53,13 +53,14 @@
   private Object connectedBluetoothSocket;
   private InputStream inputStream;
   private OutputStream outputStream;
-
+  private int sdkLevel;
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java]: You could make this final since it will always be the same for a given instance of the app.

File: appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java [hunk 2]
```diff
@@ -193,7 +194,11 @@ public final void Disconnect() {
    */
   @SimpleProperty(category = PropertyCategory.BEHAVIOR)
   public final boolean IsConnected() {
-    return (connectedBluetoothSocket != null);
+    if (sdkLevel >= SdkLevel.LEVEL_ICE_CREAM_SANDWICH) {
+      return (connectedBluetoothSocket != null && BluetoothReflection.isBluetoothSocketConnected(connectedBluetoothSocket));
+    }
+    else
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java]: `else` case should still have curly braces even for a single statement ([Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used)).

**Comment by ewpatton** [comment]
Code looks okay, but I want to test it with a device to confirm it works.

File: appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java [hunk 3]
```diff
@@ -76,7 +77,7 @@ private BluetoothConnectionBase(Form form, String logTag) {
    * This constructor is for testing purposes only.
    */
   protected BluetoothConnectionBase(OutputStream outputStream, InputStream inputStream) {
-    this((Form) null, (String) null);
+    this((Form) null, (String) null, SdkLevel.LEVEL_CUPCAKE);
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java]: Since the earliest SDK version we target is 7, you should use `LEVEL_ECLAIR_MR1` rather than `LEVEL_CUPCAKE`

File: appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java [hunk 4]
```diff
@@ -193,7 +194,12 @@ public final void Disconnect() {
    */
   @SimpleProperty(category = PropertyCategory.BEHAVIOR)
   public final boolean IsConnected() {
-    return (connectedBluetoothSocket != null);
+    if (sdkLevel >= SdkLevel.LEVEL_ICE_CREAM_SANDWICH) {
+      return (connectedBluetoothSocket != null && BluetoothReflection.isBluetoothSocketConnected(connectedBluetoothSocket));
+    }
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java]: Code style: `} else {`

File: appinventor/docs/reference/components/connectivity.html [hunk 5]
```diff
@@ -550,7 +550,7 @@ <h3>Properties</h3>
   <dt><code>HighByteFirst</code></dt>
   <dd></dd>
   <dt><code><em>IsConnected</em></code></dt>
-  <dd></dd>
+  <dd>On devices with API level 14 (LEVEL_ICE_CREAM_SANDWICH) or higher, this property returned is accurate. But on old devices with API level lower than 14, it may not return the current state of connection(e.g., it might be disconnected but you may not know until you attempt to read/write the socket.)</dd>
```
Comment (ewpatton) [inline appinventor/docs/reference/components/connectivity.html]: Now that we have markdown based documentation, you should include this in the description in the `@SimpleProperty` annotation as this file no longer exists.

File: appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java [hunk 6]
```diff
@@ -53,18 +53,19 @@
   private Object connectedBluetoothSocket;
   private InputStream inputStream;
   private OutputStream outputStream;
-
+  private final int sdkLevel;
   /**
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/BluetoothConnectionBase.java]: Include a blank line before the Javadoc.

**Comment by ellelili2025** [comment]
> I tested this using the Ev3 and IsConnected still reported true after I turned off the robot. It turns out isConnected is not as robust to the availability of the connected device as one might think. What we will probably want to do is also handle situations where an error occurs during IO and reset the internals state so that we are "disconnected"

I am even unable to reset the state to "disconnected' by closing the socket when the robot is turned off and and OI error happens.  Trying if there is another way to do it.

**Comment by ewpatton** [comment]
@ellelili2025 Code changes look okay. I'll test it in the lab and then it should be good to go.

**Comment by ewpatton** [comment]
@ellelili2025 Now that I've had a bit more time to think about this, I think what we want to do is also expose a property DisconnectOnError that controls whether this actually applies. I can imagine that some people might be surprised by the change in behavior if their code isn't robust, so we should have a way for them to configure the disconnect functionality. We should make the property False by default and explain that this property will cause the bluetooth client to automatically disconnect when an error occurs.
