### PR TITLE
Fix handling of percent lengths when changing width/height in blocks

### LINKED ISSUE #923: Width/height update on orientation change
To repeat:
1. Set the width or height of a component to a percent value
2. Set the width or height of the component to a fixed value
3. Rotate the screen

After the screen rotates, the form will apply the percent layout even though the width/height was changed to a fixed value. We need to unregister the component for a percent layout change if the width/height is set to a non-percent value.

Implement a method `unregisterPercentLength` to mirror `registerPercentLength` on `Form` so that we can remove the previously registered request for sizing.

### PR DESCRIPTION
**Pull request by ZhengCornell**
Fix #923, added LinkedHashMap for register and unregister.

### CODE REVIEW

**Comment by AppInventorWorkerBee** [comment]
Can one of the admins verify this patch?

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 1]
```diff
@@ -682,11 +684,20 @@ void ReplayFormOrientation() {
     // We first make a copy of the existing dimChanges list
     // because while we are replaying it, it is being appended to
     Log.d(LOG_TAG, "ReplayFormOrientation()");
-    ArrayList<PercentStorageRecord> temp = (ArrayList<PercentStorageRecord>) dimChanges.clone();
+    LinkedHashMap<Integer, PercentStorageRecord> temp = (LinkedHashMap<Integer, PercentStorageRecord>) dimChanges.clone();
     dimChanges.clear();         // Empties it out
-    for (int i = 0; i < temp.size(); i++) {
-      // Iterate over the list...
-      PercentStorageRecord r = temp.get(i);
+    // for (int i = 0; i < temp.size(); i++) {
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: Please remove the commented out code.

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 2]
```diff
@@ -682,11 +684,20 @@ void ReplayFormOrientation() {
...
+    //   // Iterate over the list...
+    //   PercentStorageRecord r = temp.get(i);
+    //   if (r.dim == PercentStorageRecord.Dim.HEIGHT) {
+    //     r.component.Height(r.length);
+    //   } else {
+    //     r.component.Width(r.length);
+    //   }
+    // }
+    // Iterate temp
+    for (Integer key : temp.keySet()) {
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: Rather than iterate over `keySet()`, iterate over `values()`. It will save having to do the get on the next line.

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 3]
```diff
@@ -695,8 +706,29 @@ void ReplayFormOrientation() {
     }
   }
 
+  private Integer generateHashCode(AndroidViewComponent component, PercentStorageRecord.Dim dim) {
+    if (dim == PercentStorageRecord.Dim.HEIGHT) {
+      return (component.hashCode() + dim.hashCode()) * 2 + 1;
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: You don't need to add `dim.hashCode()` here (or the next line). By virtue of adding 0 or 1 we are encoding the dimension information perfectly.

**Comment by ewpatton** [comment]
@ZhengCornell Also because this changes code that affects the companion, please rebase the change onto `ucr` and update the base branch for this PR.

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 4]
```diff
@@ -695,8 +696,29 @@ void ReplayFormOrientation() {
...
+    if (dim == PercentStorageRecord.Dim.HEIGHT) {
+      return component.hashCode() * 2 + 1;
+    } else {
+      return component.hashCode() * 2;
+    }
+  }
+
   public void registerPercentLength(AndroidViewComponent component, int length, PercentStorageRecord.Dim dim) {
-    dimChanges.add(new PercentStorageRecord(component, length, dim));
+    // dimChanges.add(new PercentStorageRecord(component, length, dim));
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: Remove commented out code.

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 5]
```diff
@@ -695,8 +696,29 @@ void ReplayFormOrientation() {
...
+    PercentStorageRecord r = new PercentStorageRecord(component, length, dim);
+    Integer key = generateHashCode(component, dim);
+    dimChanges.put(key, r);
+  }
+
+  public void unregisterPercentLength(AndroidViewComponent component, PercentStorageRecord.Dim dim) {
+    // iterate map, remove all entry match this
+    for (Integer key : dimChanges.keySet()) {
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: This code can be simplified to `dimChanges.remove(generateHashCode(component, dim));` There will be at most one thing in the map, and removing a key that isn't in the map is a no-op. It's also faster because the HashMap will provide O(1) amortized performance versus iterating over every single entry.

**Comment by ewpatton** [comment]
@AppInventorWorkerBee ok to test

File: appinventor/components/src/com/google/appinventor/components/runtime/Form.java [hunk 6]
```diff
@@ -695,8 +696,25 @@ void ReplayFormOrientation() {
...
   public void registerPercentLength(AndroidViewComponent component, int length, PercentStorageRecord.Dim dim) {
-    dimChanges.add(new PercentStorageRecord(component, length, dim));
+    PercentStorageRecord r = new PercentStorageRecord(component, length, dim);
+    Integer key = generateHashCode(component, dim);
+    dimChanges.put(key, r);
+  }
+
+  public void unregisterPercentLength(AndroidViewComponent component, PercentStorageRecord.Dim dim) {
+    // iterate map, remove all entry match this
+    for (Integer key : dimChanges.keySet()) {
```
Comment (ewpatton) [inline appinventor/components/src/com/google/appinventor/components/runtime/Form.java]: You don't need the for loop here any more. The call to `remove` on line 716 either will remove the entry if it exists or do nothing if it doesn't exist. Because it changes the map, it will result in a `ConcurrentModificationException` as written since you're modifying the loop while iterating over it.
